<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="parameters">


  <!-- Degree-to-radian conversions -->
    <xacro:property name="degrees_45" value="0.785398163"/>
    <xacro:property name="degrees_90" value="1.57079633"/>
    <xacro:property name="tube_R" value="0.05"/>


  <!-- Chassis main inertial body -->
    <xacro:property name="chassis_L" value="4"/>
    <xacro:property name="chassis_W" value="0.5"/>
    <xacro:property name="chassis_H" value="0.25"/>
    <xacro:property name="chassis_M" value="1528"/>

  <!-- Front and Rear Axles -->
    <xacro:property name="wheelbase" value="2.849"/> <!-- distance from rear axle to front axle -->

    <xacro:property name="front_axle_R" value="${tube_R}"/> <!-- radius of front axle -->
    <xacro:property name="front_axle_W" value="1.50"/>

    <xacro:property name="rear_axle_R" value="${tube_R}"/> <!-- radius of rear axle -->
    <xacro:property name="rear_axle_W" value="1.50"/>

    <!-- The specifications for a Titan(R) 550 motor could not be found, so the
         stall torque of a Mabuchi Motor(R) RS-550VC-7525 motor was used instead.

         num_spur_gear_teeth = 68
         num_pinion_gear_teeth = 19
         final_gear_ratio = (num_spur_gear_teeth / num_pinion_gear_teeth) *
           5.22 = 18.68
         stall_torque = 0.549 N m
         axle_eff_limit = ((2 * stall_torque) * final_gear_ratio) / 4 =
           5.12766 N m

         max_speed = 40 mph (30+ mph) = 17.8816 m/s
         axle_vel_limit = (2 * pi) * (max_speed / (pi * tire_dia)) =
           244.8696 rad/s -->
    <xacro:property name="axle_eff_limit" value="352.5"/>
    <xacro:property name="axle_vel_limit" value="204.8"/> <!-- 150 mph limit, given wheel radius -->

  <!-- Wheel Travel -->
    <xacro:property name="ground_clearance" value="0.10"/>
    <xacro:property name="wheel_travel_front" value="0.15"/>
    <xacro:property name="wheel_travel_rear" value="0.15"/>

  <!-- Wheels -->
    <xacro:property name="wheel_front_R" value="0.3255"/>
    <xacro:property name="wheel_front_H" value="0.15"/>
    <xacro:property name="wheel_front_M" value="18"/>

    <xacro:property name="wheel_rear_R" value="0.3255"/>
    <xacro:property name="wheel_rear_H" value="0.15"/>
    <xacro:property name="wheel_rear_M" value="18"/>

  <!-- Shocks -->
    <xacro:property name="shock_R" value="${tube_R}"/> <!-- shock cylinder radius -->
    <xacro:property name="shock_H" value="${wheel_travel_front}"/> <!-- shock length -->
    <xacro:property name="shock_M" value="20"/> <!-- shock mass -->
    <xacro:property name="shock_z_offset" value="0"/> <!-- offset from origin of chassis main body -->
    <xacro:property name="shock_y_offset" value="${chassis_W/2 + 2 * shock_R}"/> <!-- offset from origin of chassis main body -->
    <xacro:property name="shock_wall_thickness" value="0.002"/>

    <!-- shock_eff_limit is 2 * ((shock_stroke / 2) * shock_spring_constant) N.
         shock_stroke is 0.028575 meters. shock_spring_constant, an approximation
         of a Traxxas Ultra Shock shock absorber spring's constant, is
         437.817 N/m. -->
    <xacro:property name="shock_eff_limit" value="37479"/>
    <xacro:property name="shock_vel_limit" value="1000"/>

    <xacro:property name="shock_spring_const" value="37479"/>
    <xacro:property name="wheel_z_offset" value="${chassis_M/4*9.81 / shock_spring_const}"/>

  <!-- Steering -->
    <xacro:property name="steer_link_R" value="${tube_R}"/>
    <xacro:property name="steer_link_H" value="0.10"/>
    <xacro:property name="steer_link_M" value="5"/>
    <!-- These constants are used to simulate a Traxxas 2056 servo operated at
         6 V. servo_stall_torque is measured in N m. servo_no_load_speed is
         measured in rad/s. -->
    <xacro:property name="steer_stall_torque" value="200"/>
    <xacro:property name="steer_no_load_speed" value="4.553"/>



</robot>
