<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rear_axle_assembly">



  <!-- steer_link -->
    <link name="steer_link">
      <visual>
        <origin xyz="0 ${steer_link_Y_offset} 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${steer_link_R}" length="${steer_link_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${steer_link_R}" length="${steer_link_H}"/>
        </geometry>
      </collision> -->

      <xacro:thick_walled_tube_inertial
          inner_rad="${steer_link_R - thick_wall}" outer_rad="${steer_link_R}"
          height="${steer_link_H}" mass="${steer_link_M}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:thick_walled_tube_inertial>
    </link>

  <!-- JOINT steer_link TO chassis -->
    <joint name="steering_joint" type="revolute">
      <parent link="chassis"/>
      <child link="steer_link"/>
      <origin xyz="${rear_axle_X_offset} 0 ${rear_axle_Z_offset}"/>
      <axis xyz="0 0 1"/>
      <limit lower="${-degrees_45}" upper="${degrees_45}"
             effort="${steer_stall_torque}" velocity="${steer_no_load_speed}"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>

    <transmission name="steering_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="steering_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="steering_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>


  <!-- wheel_front_left -->
    <link name="rear_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_rear_R}" length="${wheel_rear_H}"/>
        </geometry>
        <material name="tire_mat"/>
      </visual>

      <!-- <visual>
        <origin xyz="0 0 0" rpy="${-degrees_90} 0 0"/>
        <geometry>
            <mesh filename = "package://rc_car_description/meshes/wheel.dae" scale = "0.125 0.125 0.23" />
        </geometry>
        <material name="tire_mat"/>
      </visual> -->

      <collision>
        <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_rear_R}" length="${wheel_rear_H}"/>
        </geometry>
        <!-- <max_contacts>1</max_contacts> -->
      </collision>

      <xacro:thick_walled_tube_inertial
          inner_rad="${wheel_rear_R - thick_wall}" outer_rad="${wheel_rear_R}"
          height="${wheel_rear_H}" mass="${wheel_rear_M}">
      <origin xyz="0 0 0" rpy="${degrees_90} 0 0"/>
      </xacro:thick_walled_tube_inertial>
    </link>

  <!-- JOINT wheel_front_left TO steer_link_front_left -->
    <joint name="rear_axle" type="continuous">
      <parent link="steer_link"/>
      <child link="rear_wheel"/>
      <origin xyz="0 0 0 "/>
      <axis xyz="0 1 0"/>
      <!-- <dynamics damping="0.01"/> -->
      <limit effort="${axle_eff_limit}" velocity="${axle_vel_limit}"/>
    </joint>

    <transmission name="rear_axle_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="rear_axle">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="rear_axle_act">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>




    <gazebo reference="rear_wheel">
        <material>Gazebo/Orange</material>
	      <mu1>0.5</mu1>
        <mu2>0.5</mu2>
        <kp>1e8</kp>
    		<!-- <kp>1e8</kp> -->
    		<kd>1</kd>
    		<minDepth>0.001</minDepth>
    		<maxVel>10.0</maxVel>
    </gazebo>


</robot>
