<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="XV-11">
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="laser_head_M" value="0.200"/>
  <xacro:property name="laser_head_wall_thickness" value="0.01"/>
  <xacro:property name="laser_head_R" value="0.04"/>
  <xacro:property name="laser_head_H" value="0.02"/>
  <xacro:macro name="XV-11" params="parent name topic *origin">

    <!-- <joint name="xv11_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="xv11_base"/>
    </joint> -->

    <!-- XV11 Base -->
    <!-- <link name="xv11_base">
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
      <box size="0.10 0.08 0.02"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.10 0.08 0.02"/>
        </geometry>
        <material name="red"/>
      </visual>

      <inertial>
        <mass value="1e-5" />
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
      </inertial>
    </link> -->

    <!-- XV-11 Head -->
    <link name="xv11_head">
      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
      <cylinder radius="0.05" length="0.02"/>
        </geometry>
      </collision> -->

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.05" length="0.02"/>
        </geometry>
        <material name="red"/>
      </visual>

      <xacro:thick_walled_tube_inertial
          inner_rad="${laser_head_R - laser_head_wall_thickness}" outer_rad="${laser_head_R}"
          height="${laser_head_H}" mass="${laser_head_M}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:thick_walled_tube_inertial>
    </link>

    <joint name="xv11_head_joint" type="continuous">
      <!-- <origin xyz="0 0 0.02" rpy="0 0 0" /> -->
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="xv11_head"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.01" friction="0.0"/>
      <limit effort="2" velocity="100"/>
    </joint>

    <transmission name="xv11_head_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="xv11_head_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="xv11_head_actuator">
        <!-- This hardwareInterface element exists for compatibility
             with ROS Hydro. -->
        <hardwareInterface>EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>



    <!-- hokuyo -->
    <gazebo reference="xv11_head">
      <sensor type="ray" name="head_xv11_laser">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>1800</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>5.0</max>
            <resolution>0.02</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <!-- Noise parameters based on published spec for Hokuyo laser
                 achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
                 stddev of 0.01m will put 99.7% of samples within 0.03m of the true
                 reading. -->
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_head_xv11_controller" filename="libgazebo_ros_laserB.so">
          <topicName>xv11_scan</topicName>
          <frameName>xv11_head</frameName>
        </plugin>
      </sensor>
    </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_laser_xv11" filename="libgazebo_ros_laser_xv11.so">
      <PID>0.08 0.01 0</PID>
      <Torque>2.0</Torque>
      <RPM>300</RPM>
      <Velocity>100</Velocity>
    </plugin>
  </gazebo>

  </xacro:macro>
</robot>
